 services: 
  client:
    build:
      context: client
      target: development
    ports:
      - 5173:5173
    stdin_open: true
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
     - react-express
    depends_on:
      - server

  server:
    restart: always
    build:
      context: server
      target: development
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
   # depends_on:
     # - mongo
    environment:
      NODE_ENV: development
      SALT_ROUNDS: 2
      PORT: 3000
      DEV_MONGO_DB_URL: "mongodb+srv://sreekanthreddy:zjx8oAFdoKbqVZfJ@webstack.bcp82.mongodb.net"
      DEV_DB_NAME: THS_X
      DEV_JWT_SECRET_KEY: "THSC24"
      STAGING_JWT_SECRET_KEY: "THSC24"
      PROD_JWT_SECRET_KEY: "THSC24"
      GMAIL_SMTP_HOST: smtp.gmail.com
      GMAIL_SMTP_PORT: 587
      GMAIL_SMTP_USER: sreekanthreddy9381@gmail.com
      GMAIL_SMTP_PASS: "wytw uelp rthb uecb"
    networks:
      #- express-mongo
      - react-express
    expose:
      - 3000

#  mongo:
    # Since MongoDB is hosted on MongoDB Atlas, we don't need a container for it anymore.
    # You can remove this service, as Atlas is being used instead.
    # You can keep it in case you want to use a local MongoDB for testing.
    # However, we will rely on the MongoDB Atlas connection URL in the backend service.
#    restart: always
#    image: mongo:4.2.0
#    volumes:
#      - mongo_data:/data/db
 #   networks:
 #     - express-mongo

#volumes:
 # mongo_data:

 networks:
  react-express:
  #express-mongo: