version: "3.8"

services:
  client:
    build:
      context: client
      target: development
    ports:
      - 5173:5173
    stdin_open: true
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - server

  server:
    build:
      context: server
      target: development
    restart: always
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: "mongodb://mongo:27017/THS_X"
      JWT_SECRET_KEY: "THSC24"
      GMAIL_SMTP_HOST: smtp.gmail.com
      GMAIL_SMTP_PORT: 587
      GMAIL_SMTP_USER: sreekanthreddy9381@gmail.com
      GMAIL_SMTP_PASS: "wytw uelp rthb uecb"
    networks:
      - express-mongo
      - react-express
    expose:
      - 3000
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.6
    restart: always
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      - express-mongo
    ports:
      - 27017:27017

volumes:
  mongo_data:

networks:
  react-express:
  express-mongo:
